print(True or False)
print(True or False)
print(True or False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True and False)
print(True or False)
print(True or False)

num = int(input("enter your number"))
print(num>10 or False)